// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCci6eijycGufbI0cwYQZDP0KRqu-b2j8Q',
    appId: '1:773861073676:web:192d073ee779264ada1f29',
    messagingSenderId: '773861073676',
    projectId: 'sevgilimeapp',
    authDomain: 'sevgilimeapp.firebaseapp.com',
    databaseURL: 'https://sevgilimeapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sevgilimeapp.firebasestorage.app',
    measurementId: 'G-95DY5P6S5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXUKl2rHlTz1tvC7NS1R6qlAVbqPVTZk',
    appId: '1:773861073676:android:2f436e38cc88dc9eda1f29',
    messagingSenderId: '773861073676',
    projectId: 'sevgilimeapp',
    databaseURL: 'https://sevgilimeapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sevgilimeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8GqI07u3lL_tzKpTGhGgT9sTPm8LeHU',
    appId: '1:773861073676:ios:636c079e3fde33bada1f29',
    messagingSenderId: '773861073676',
    projectId: 'sevgilimeapp',
    databaseURL: 'https://sevgilimeapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sevgilimeapp.firebasestorage.app',
    iosBundleId: 'com.enes.sevgilime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8GqI07u3lL_tzKpTGhGgT9sTPm8LeHU',
    appId: '1:773861073676:ios:636c079e3fde33bada1f29',
    messagingSenderId: '773861073676',
    projectId: 'sevgilimeapp',
    databaseURL: 'https://sevgilimeapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sevgilimeapp.firebasestorage.app',
    iosBundleId: 'com.enes.sevgilime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCci6eijycGufbI0cwYQZDP0KRqu-b2j8Q',
    appId: '1:773861073676:web:e1e11a010556331fda1f29',
    messagingSenderId: '773861073676',
    projectId: 'sevgilimeapp',
    authDomain: 'sevgilimeapp.firebaseapp.com',
    databaseURL: 'https://sevgilimeapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sevgilimeapp.firebasestorage.app',
    measurementId: 'G-4XPHHF5CJM',
  );
}
